"""Python-native bindings for Betterleaks."""

from ._version import __version__
from .config import BetterleaksConfig, Expr, Extend, RequiredRule, Rule, Validation
from .exceptions import (
    ConfigFormatError,
    InvalidScanRequestError,
    NativeCallError,
    NativeLibraryError,
    NativeLibraryNotFoundError,
    NativeScanError,
    PyBetterleaksError,
    ScanConfigError,
    ScanFailedError,
    ScanTargetError,
    ScanTimeoutError,
    UnsupportedScanError,
    raise_for_errors,
    scan_exception_from_result,
)
from .models import Finding, ScanError, ScanResult
from .scanner import (
    SUPPORTED_GIT_SCOPES,
    GitScope,
    betterleaks_version,
    scan_dir,
    scan_dir_async,
    scan_git,
    scan_git_async,
    scan_text,
    scan_text_async,
)

__all__ = [
    "SUPPORTED_GIT_SCOPES",
    "BetterleaksConfig",
    "ConfigFormatError",
    "Expr",
    "Extend",
    "Finding",
    "GitScope",
    "InvalidScanRequestError",
    "NativeCallError",
    "NativeLibraryError",
    "NativeLibraryNotFoundError",
    "NativeScanError",
    "PyBetterleaksError",
    "RequiredRule",
    "Rule",
    "ScanConfigError",
    "ScanError",
    "ScanFailedError",
    "ScanResult",
    "ScanTargetError",
    "ScanTimeoutError",
    "UnsupportedScanError",
    "Validation",
    "__version__",
    "betterleaks_version",
    "raise_for_errors",
    "scan_dir",
    "scan_dir_async",
    "scan_exception_from_result",
    "scan_git",
    "scan_git_async",
    "scan_text",
    "scan_text_async",
]
